#!/bin/bash
# Copyright 2018 Minim Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ $(id -u) != "0" ] && exec sudo "$0"

seems_to_be_running() {
    local chk=$(service "$1" status | grep "active (running)")
    if [[ -z "$chk" ]]; then
        return 1
    fi
    return 0
}
start_retry() {
    local -i tries=0
    while (( tries < 3 )) && ! seems_to_be_running "$1"; do
        service "$1" start
        sleep 1
        tries=$(( tries + 1 ))
    done
    return 0
}

declare -i interactively=1
if [[ "$1" == "--no-interactive" ]]; then
    interactively=0
fi

if (( ! interactively )) && [[ ! -f "$UNUM_ETC_DIR/extras.conf.sh" ]]; then
    echo 'unum is unconfigured, please re-run without `--no-interactive`:'
    echo '    minim-config'
fi

# Run in a sub-process to route output to a log file
{
    service hostapd stop
    service dnsmasq stop
    service wpa_supplicant stop
    service unum stop

    killall -9 hostapd dnsmasq wpa_supplicant unum

    rfkill unblock wifi

    rm -fv /var/opt/unum/unum.key /var/opt/unum/unum.pem
} >> /var/opt/unum/minim-config.log 2>&1

# Configuration
declare interactive_flag=
if (( ! interactively )); then
    interactive_flag="--no-interactive"
fi
/opt/unum/extras/sbin/config_interfaces.sh "$interactive_flag"
/opt/unum/extras/sbin/config_hostapd.sh "$interactive_flag"
/opt/unum/extras/sbin/config_dnsmasq.sh
/opt/unum/extras/sbin/config_routing.sh

# Run in a sub-process to route output to a log file
{
    . /etc/opt/unum/extras.conf.sh

    ifconfig "$ifname_lan" down
    ip link set "$ifname_lan" address "$hwaddr_lan"
    ifconfig "$ifname_lan" up

    sed -i -e 's:/var/opt/unum:/etc/opt/unum:g' /etc/default/dnsmasq
    sed -i -e 's:/var/opt/unum:/etc/opt/unum:g' /etc/default/hostapd

    sleep 1

    systemctl enable unum-aio

    systemctl disable unum
    systemctl disable hostapd
    systemctl disable dnsmasq

    # leave wpa_supplicant disabled
    systemctl disable wpa_supplicant

    start_retry hostapd
    start_retry dnsmasq
    start_retry unum
} >> /var/opt/unum/minim-config.log 2>&1
