#!/bin/sh /etc/rc.common
# (C) 2021 minim.co

# Turn on Green LED at boot time
START=09
boot() {
  echo 255 > /sys/class/leds/green/brightness
  echo 0 > /sys/class/leds/red/brightness
  echo 0 > /sys/class/leds/blue/brightness
}
